hashmgt: hashmgt.cpp hashmap.o hashmap.h
	g++ -g hashmgt.cpp hashmap.o -o hashmgt
hashmap.o: hashmap.cpp hashmap.h
	g++ -g -c hashmap.cpp -o hashmap.o
fibo: fibo.cpp hashmap.o hashmap.h
	g++ -g fibo.cpp hashmap.o -o fibo