traversaltest: test.cpp graphtraversal.o graphtraversal.h
	g++ -g test.cpp graphtraversal.o -o traversaltest
graphtraversal.o: graphtraversal.cpp graphtraversal.h
	g++ -g -c graphtraversal.cpp -o graphtraversal.o